load("//tools/buck:cxxbridge_cxx_library.bzl", "cxxbridge_cxx_library")

rust_test(
    name = "test",
    srcs = ["test.rs"],
    deps = [":ffi"],
)

bridge_srcs = [
    "ffi/lib.rs",
    "ffi/module.rs",
]

rust_library(
    name = "ffi",
    srcs = bridge_srcs,
    crate = "cxx_test_suite",
    deps = [
        ":impl",
        "//:cxx",
    ],
)

cxxbridge_cxx_library(
    name = "impl",
    crate_name = "cxx-test-suite",
    bridge_srcs = bridge_srcs,
    srcs = ["ffi/tests.cc"],
    headers = {
        "tests.h": "ffi/tests.h",
    },
    deps = ["//:core"],
)
