load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    default_edition = None,
    rustc_flags = ["-Clink-arg=-fuse-ld=lld"],
    rustdoc_flags = ["-Zunstable-options"],  # doc builds use unstable '--extern-html-root-url'
    visibility = ["PUBLIC"],
)
