[package]
name = "cxx-handles-demo"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
cxx = "0.5"

[build-dependencies]
cxx-build = "0.5"

[workspace]
