[package]
name = "no-causes"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
cxx = { path = ".." }

[build-dependencies]
cxx-build = { path = "../gen/build" }

[workspace]
